name: RGBColorPicker
main: me.Dariela.rgbcolorpicker.RGBColorPicker
softdepend: [PlaceholderAPI]
author: Dariela
version: ${project.version}
api-version: 1.17
commands:
   rgbcolorpicker:
      aliases: [rcp]
      description: Main command
      usage: /<command>